name: "HA Diagnostic"
version: "0.2.0"
slug: "hadiagnostic"
description: "Diagnostique les erreurs et les add-ons Home Assistant qui ne démarrent pas"
url: "https://github.com/olivierguntern/HAdiagnostic"
arch:
  - amd64
  - armv7
  - aarch64
  - i386
startup: application
boot: auto
hassio_api: true
hassio_role: manager
ingress: true
ingress_port: 8099
panel_icon: mdi:stethoscope
panel_title: "HA Diagnostic"
options: {}
schema: {}
